// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Kru_Demo","status":true,"description":"1.0.0 Helper for demos of plugins.","parameters":{"Path":"/demo/shared/","Container":"game"}},
{"name":"Kru_Core","status":true,"description":"1.0.0 Shared base for many Krues8dr plugins","parameters":{"---General---":""}}
];
